baseURL = 'https://news.hicar.cool/'
languageCode = 'zh'
title = 'HiCar最新消息'
theme = 'paper'


[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  rss = true                                # show rss icon

  # home page profile
  avatar = 'https://youniqiaofu.com/images/avatar.png'                 # gravatar email or image url
  name = '油腻樵夫'
  bio = 'HiCar首席吹捧官'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'https://cdn.v2ex.com/gravatar/'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon


